### ISSUE TITLE
ideas to use this with input type date

### ISSUE THREAD

**Issue by anoopsinghbayes** [awerlang/angular-easy-masks#1]
great directive!

i would like this to work with input type date.

**Comment by awerlang** [comment]
Hello Anoopsingh, thanks for your feedback!

Which data type do you use for date? And do you target IE?, as others browsers and mobile already have native `type=date`.

**Comment by anoopsinghbayes** [comment]
ok what i mean to say is the browser that do not support HTML 5 date type we can follow the path angularjs follows from this link[https://docs.angularjs.org/api/ng/input/input%5Bdate%5D]

**Comment by awerlang** [comment]
I've update the road map to consider this feature. I've also made a plnkr to demonstrate current state of things: http://plnkr.co/edit/PHIrXRVYWWku3L7Gmvma?p=preview

The only thing is I'd prefer to enter date according to user language settings, even on unsupported browsers. Perhaps a second directive should handle this case.
