### ISSUE TITLE
How can we catch error with ng-messages ?

### ISSUE THREAD

**Issue by sebastienvermeille** [awerlang/angular-easy-masks#14]
Hello first of all thank you for this great directive :+1:  

I try to display an error message when the directive says it is wrong.

I tryed with <ng-message when="pattern">invalid data</ng-message> but it seems you use another key ?

Any advice around it ? Thank you in advance for your help

**Comment by awerlang** [comment]
Hi, nice to hear from you!

The key in the $error object is `mask`. Hope it helps.

**Comment by sebastienvermeille** [comment]
Hi @awerlang perfect I will try it on monday :) thank you very much
