### ISSUE TITLE
Allow removing mask entirely before updating the model

### ISSUE THREAD

**Issue by ChaudhryAtif** [awerlang/angular-easy-masks#15]
Great and simple directive!

Similar to the 'removeSeparators' option, perhaps add another option called 'removeMask' (or whatever seems reasonable), which would remove all formatting when saving, but will show masked inside the input.

Example (first with removeSeparator, second with removeMask):
`<input type="text" ng-model="ctrl.field" wt-easy-mask="(999) 999-9999" wt-easy-mask-options="{removeSeparators: true}" placeholder="Type your Phone Number" />`
Value: 1234567890
Input displays: (123) 456-7890
Model stores: (123)4567890

`<input type="text" ng-model="ctrl.field" wt-easy-mask="(999) 999-9999" wt-easy-mask-options="{removeMask: true}" placeholder="Type your Phone Number" />`
Value: 1234567890
Input displays: (123) 456-7890
Model stores: 1234567890

One use case would be if I want to store clean data in the database, but still display masked value inside input.

**Comment by awerlang** [comment]
> Great and simple directive!

Thanks!

`removeSeparators` removes `.`, `/`, `-` and `whitespace` from model value. I was wondering if `(`, `)`, `+` and others should be included too. And why not everything that's not an alphanumeric character. That's how input is handled anyways. The cons is that it's a breaking change. But I guess it wouldn't be clear to distinguish between two options. Thoughts?

**Comment by ChaudhryAtif** [comment]
You could create a new option that removes all but alphanumeric, and mark removeSeparators to be deprecated in a future version. removeMask seems more descriptive for the functionality because you are adding a mask, and 'removeMask' will remove it before saving.

**Comment by awerlang** [comment]
Sounds good. Would you like to send a PR?

**Comment by ChaudhryAtif** [comment]
PR sent (my first ever!)

**Comment by awerlang** [comment]
It's the first PR on this repo too! I find it good to do PRs, there's always something we can learn from the process. Hope you find other opportunities to do it again (here, elsewhere)!

And thanks for contributing! I left some comments on the PR already.

**Comment by ChaudhryAtif** [comment]
Pushed again. Not sure what you meant by 'Squash before pushing'. Also, I noticed that it does not run all of your Karma tests. Before it stopped after running 67 of 71, and now it stops after running 69 of 71 (I added 2). You might want to look into that.

**Comment by awerlang** [comment]
Squash means "rewrite" git history turning a number of commits into a single one. But don't worry, not a big deal. I will take a look on the tests asap, it's been a long time since I last had to run them.

**Comment by awerlang** [comment]
The tests are successful. Those 4 tests are disabled, I kept them for historical reasons.

I released your contrib in v0.2.2. Thanks!

**Comment by ChaudhryAtif** [comment]
Sounds good. Thanks!
