### ISSUE TITLE
Allow empty placeholder

### ISSUE THREAD

**Issue by ChaudhryAtif** [awerlang/angular-easy-masks#18]
Currently, if there is no placeholder or if the placeholder is set to empty string, it uses the Mask as the placeholder.

Add an option (i.e. emptyPlaceholder or removePlaceholder) to wtEasyMaskOptions if no placeholder of any kind is desired.

`<input type="text" ng-model="form.middleInitial" wt-easy-mask="Z" wt-easy-mask-options="{emptyPlaceholder: true}" />`

**Comment by ChaudhryAtif** [comment]
#20 PR sent

**Comment by awerlang** [comment]
Closed by #20
